config/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

from ecfgrades.grades import views


urlpatterns = [
    path('grades/', include('ecfgrades.grades.urls')),
    path('statistics/', include('ecfgrades.statistics.urls')),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

ecfgrades/grades/urls.py
from django.urls import path

from . import views

app_name = 'grades'
urlpatterns = [
    # e.g. grades/
    path('', views.index, name='index'),
    # e.g. /grades/5/
    path('<str:player_ref>/', views.detail, name='detail'),
]

ecfgrades/statistics/urls.py
from django.urls import path

from . import views

app_name = 'statistics'
urlpatterns = [
    path('', views.index, name='index'),
    path('api/distrib/', views.distrib, name='distrib'),
]

ecfgrades/grades/models.py
from django.db import models


# -----------------------------------------------------------------------------
class Player(models.Model):
    """
    Ref,Name,Sex,JrAge,Cat,Grade,Grade1,Games,RCat,RGrade,RGrade1,RGames,
    ClubNam1,ClubNam2,ClubNam3,ClubNam4,ClubNam5,ClubNam6,FIDECode,Nation
    """
    ref = models.CharField(max_length=7, primary_key=True)
    name = models.CharField(max_length=60)
    sex = models.CharField(max_length=1)

    def fullname(self):
        names = self.name.split(',')
        return ''.join(names[1:])+' '+names[0]

    class Meta:
        db_table = 'player'
        unique_together = ['ref', 'name', 'sex']


# -----------------------------------------------------------------------------
class Club(models.Model):
    name = models.CharField(max_length=60)
    is_area = models.BooleanField()

    def clubname(self):
        if self.is_area:
            return self.name + '[ area ]'
        return self.name

    class Meta:
        db_table = 'club'
        unique_together = ['name', 'is_area']


# -----------------------------------------------------------------------------
class Grade(models.Model):
    player = models.ForeignKey(
        Player,
        on_delete=models.PROTECT,
        related_name='%(class)s_grade',
    )
    grading_date = models.DateField()
    age = models.IntegerField(null=True)
    fidecode = models.CharField(max_length=10)
    nation = models.CharField(max_length=3)
    category = models.CharField(max_length=1)
    grade = models.IntegerField(null=True)
    previous_grade = models.IntegerField(null=True)
    num_games = models.IntegerField()
    rapid_category = models.CharField(max_length=1)
    rapid_grade = models.IntegerField(null=True)
    rapid_previous_grade = models.IntegerField(null=True)
    rapid_num_games = models.IntegerField(null=True)
    club1 = models.ForeignKey(
        Club, on_delete=models.PROTECT, related_name='%(class)s_club1', null=True)
    club2 = models.ForeignKey(
        Club, on_delete=models.PROTECT, related_name='%(class)s_club2', null=True)
    club3 = models.ForeignKey(
        Club, on_delete=models.PROTECT, related_name='%(class)s_club3', null=True)
    club4 = models.ForeignKey(
        Club, on_delete=models.PROTECT, related_name='%(class)s_club4', null=True)
    club5 = models.ForeignKey(
        Club, on_delete=models.PROTECT, related_name='%(class)s_club5', null=True)
    club6 = models.ForeignKey(
        Club, on_delete=models.PROTECT, related_name='%(class)s_club6', null=True)

    def gradenum(self):
        return self.grade or ''

    def agenum(self):
        return self.age or ''

    class Meta:
        db_table = 'grade'

ecfgrades/grades/forms.py
from django import forms
from .models import Grade


# -------------------------------------------------------------------------
def get_timepoints():
    return [
        (t, t.strftime('%b %Y'))
        for t in (Grade.objects.
                  distinct().
                  order_by('-grading_date').
                  values_list('grading_date', flat=True))
    ]


# -------------------------------------------------------------------------
class PlayerForm(forms.Form):
    name = forms.CharField(label='Player name', max_length=100)
    timepoint = forms.ChoiceField(label='Year/month', choices=get_timepoints())

ecfgrades/grades/views.py
from datetime import datetime as dt
from django.shortcuts import get_object_or_404, render

from .models import Player, Grade
from .forms import PlayerForm


# -------------------------------------------------------------------------
def index(request):
    grades = []
    timepoint = None
    if request.method == 'POST':
        form = PlayerForm(request.POST, label_suffix='')
        if form.is_valid():
            # ChoiceField in forms produces strings
            timepoint = dt.strptime(form.cleaned_data['timepoint'], '%Y-%m-%d')
            grades = (Grade.objects.
                      filter(grading_date=timepoint).
                      filter(player__name__icontains=form.cleaned_data['name']).
                      order_by('player__name'))
    else:
        form = PlayerForm()

    context = {'grades': grades[:100], 'timepoint': timepoint, 'form': form}
    return render(request, 'grades/index.html', context)


# -------------------------------------------------------------------------
def detail(request, player_ref):
    player = get_object_or_404(Player, pk=player_ref)
    return render(request, 'grades/detail.html', {'player': player})

ecfgrades/statistics/views.py
from django.shortcuts import render
from django.http import JsonResponse

from ecfgrades.grades.models import Grade


# -----------------------------------------------------------------------------
def index(request):
    return render(request, 'statistics/index.html')


# -----------------------------------------------------------------------------
def distrib(request):
    data = (Grade.objects.
            filter(grading_date='2020-07-01').
            exclude(grade__isnull=True).
            values_list('grade', flat=True))

    return JsonResponse(list(data), safe=False)

ecfgrades/grades/templates/grades/detail.html
{% extends 'base.html' %}

{% load static %}
{# load the Bootstrap tag library #}
{% load bootstrap4 %}

{% block content %}
{{ block.super }}

<h1>{{ player.fullname }}</h1>

{% comment %}
<p>{{ player.grade }}</p>
<p>{{ player.clubnam1_text }}</p>
{% endcomment %}

{% endblock content %}

ecfgrades/grades/templates/grades/index.html
{% extends 'base.html' %}

{% load static %}
{# load the Bootstrap tag library #}
{% load bootstrap4 %}

{% block content %}
{{ block.super }}

<p class="title"><i class="fas fa-chess-bishop"></i>
Search for a player in the grading database
<i class="fas fa-chess-bishop"></i></p>
<hr>

<form action="/grades/" method="POST">
  {% csrf_token %}
  <p class="title">
  {{ form.name }}
  {{ form.timepoint }}
  <input type="submit" value="Search" />
  </p>
</form>

{% if grades %}
  <div class="info">{{ timepoint|date:"F Y" }}: {{ grades|length }} players</div>

  <table class="table tablesorter table-bordered">
  <thead>
    <tr>
    <th>Ref</th>
    <th>Name</th>
    <th>Sex </th>
    <th>Grade </th>
    <th>Age </th>
    <th>Club</th>
    <th>Category </th>
  </tr>
  </thead>
  <tbody>
    {% for g in grades %}
    <tr>
      <td>{{ g.player_id }}</td>
      <td><a href="{% url 'grades:detail' g.player_id %}">{{ g.player.fullname }}</a></td>
      <td>{{ g.player.sex }}</td>
      <td>{{ g.gradenum }}</td>
      <td>{{ g.age|default_if_none:"" }}</td>
      <td>{{ g.club1.clubname }}</td>
      <td>{{ g.category }}</td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
<!--
  <div id="pager" class="pager">
    <form>
      <img src="static/first.png" class="first"/>
      <img src="static/prev.png" class="prev"/>
      <input type="text" class="pagedisplay"/>
      <img src="static/next.png" class="next"/>
      <img src="static/last.png" class="last"/>
      <select class="pagesize">
        <option selected="selected" value="10">10</option>
        <option value="20">20</option>
        <option value="30">30</option>
        <option value="40">40</option>
      </select>
    </form>
  </div>
-->
{% endif %}

{% endblock content %}

ecfgrades/statistics/templates/statistics/index.html
{% extends 'base.html' %}

{% load static %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/d3.v4.min.js' %}"></script>
<script src="{% static 'js/histogram.js' %}"></script>
{% endblock scripts %}

{% block content %}
{{ block.super }}

<p class="info">All players at 2020-07-01</p>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <svg id="graph" width="960" height="600" style="border: 1px solid gray;"></svg>
    </div>
</div>

<script>
d3.json("/statistics/api/distrib", function(data) { draw(data); });
</script>

{% endblock content %}

ecfgrades/templates/base.html
{% load static %}
{# load the Bootstrap tag library #}
{% load bootstrap4 %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}ECF Grades{% endblock title %}
    </title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">

    {% block stylesheets %}
      {% bootstrap_css %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/tablesorter.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.tablesorter.pager.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-free-5.12.1-all.min.css' %}">
    {% endblock stylesheets %}

    {% block scripts %}
    {% bootstrap_javascript jquery='full' %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
    <script src="{% static 'js/jquery.tablesorter.pager.js' %}"></script>
    <script>
    $(document).ready(function() {
        $("table")
        .tablesorter({widthFixed: true, widgets: ['zebra']})
        //.tablesorterPager({container: $("#pager")});
    });
    </script>
    {% endblock scripts %}

  </head>

<body class="d-flex flex-column h-100">

<header class="bg-primary">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-custom fixed-top navbar-expand-lg">
    <div class="container">

    <a class="navbar-brand nav-link ml-0 mr-2 mb-0 mt-0" href="#">ECF grades database</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link mr-2" href="/">
                <i class="fas fa-search" aria-hidden="true"></i> Search</a>
            </li>
            <li class="nav-item">
                <a class="nav-link mr-2" href="/statistics">
                <i class="far fa-chart-bar" aria-hidden="true"></i> Statistics</a>
            </li>
        </ul>

    </div>  <!-- navbar-collapse -->
    </div>  <!-- container -->

    </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container-fluid">
    {% block content %}

    {% endblock content %}
    </div>
</main>

</body>
</html>